### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by norbou2** [fluentform/fluentform#275] opened 2023-02-11 18:35 UTC
Hello, I cannot say, that this is a bug, but I am getting this PHP Notice:
[11-Feb-2023 17:34:02 UTC] PHP Notice:  A non well formed numeric value encountered in /wp-content/plugins/fluentformpro/src/Payments/Components/MultiPaymentComponent.php on line 153

I am sure, that I don't use any payments in the forms, just the calculation of the price. In that case all amounts are prefilled as numbers, so I don't know, what does the notice means.

Some ideas for involved:
https://stackoverflow.com/questions/6136430/a-non-well-formed-numeric-value-encountered

**Comment by nkb-bd** [comment] 2023-02-13 04:17
Can you share your form JSON file, we will try to recreate the issue.
Thanks

**Comment by norbou2** [comment] 2023-02-15 14:31
Hi, sure. The form is still in development. 
[fluentform-export-forms-1-15-02-2023.zip](https://github.com/fluentform/fluentform/files/10744024/fluentform-export-forms-1-15-02-2023.zip)

**Comment by HrDelwar** [comment] 2024-01-26 10:25
@norbou2 Sorry for the delay, with recent FluentForm version 5.1.7 issue could not reproduced. Hope it's resolved. We are closing the issue. If this doesn't resolve let us know with a [support ticket](https://support.wpmanageninja.com/#/tickets)

**Closed by HrDelwar** 2024-01-26 10:25 UTC
